name: Test Email Step

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step with email 24f1000531@ds.study.iitm.ac.in
        run: echo "This step name contains the email address"
